apiVersion: training.artway.ai/v1
kind: TJob
metadata:
  name: torch-imagenet
spec:
  framework: torch
  tasks:
  - name: torch-imagenet
    replicas: 2
    template:
      spec:
        containers:
          - name: torch
            image: registry.baidubce.com/kuizhiqing/torch-imagenet:v1
            command: ["python","-m","torch.distributed.run","train.py"]
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            resources:
              limits:
                nvidia.com/gpu: 2
        volumes:
        - name: dshm
          emptyDir:
            medium: Memory
