apiVersion: training.artway.ai/v1
kind: TJob
metadata:
  name: tjob-sample
spec:
  tasks:
  - name: tt
    replicas: 5
    template:
      spec:
        containers:
          - name: test
            image: registry.baidubce.com/kuizhiqing/centos:7
            imagePullPolicy: Always
            command:
            - sleep
            args:
            - 1d
    
    
